Loading and saving from Google CLoud Datastore working! (database.clj)
Lots of playing around with the project.clj exclusions and manual inclusions to remove conflict of 2 different
Google Protobuf versions. Now using older version of Google database API. Test increasing version.

Attempt to move to latest DataStore API 1.37 does bring back
the original error even when doing suggested exclusions:
NoSuchMethodError com.google.protobuf.AbstractMessageLite$Builder.addAll